### ISSUE TITLE
No Display on Left CDU in Spad.Next

### ISSUE THREAD

**Issue by gksqd71** [dementedmonkey/cj4-mcdu#12]
I have an issue with the Left CDU not displaying anything on Page 2 of 5.

I have followed Les' tutorial on YT on how to configure the device with your mod. I went into settings and enabled the Application.Web.Enable and also enabled Application.MSFS.fbwWebSockets. My socket ports are 8380 and 8088 respectively and I have the latest version of the WT CJ4 (0.12.12)
I also have the Enable CockpitMaster Support enabled in Other Devices. 

I have the mod in my Addons Linker and it is throwing a shortcut into my community folder, so I don't understand why it isn't working. I have the SPAD menu showing on page 1, but nothing else after that.

Is there another step I overlooked? If you could please help me, it would be greatly appreciated!

EDIT: I installed the 0.12.11 version as mentioned in the readme and I moved the mod directly into the Community folder and I am still getting the same result as above.

**Comment by dementedmonkey** [comment]
It's OK to use the 0.12.12 version of the CJ4 mod.   It came out after my last release, and has a few fixes for the latest Sim Update that don't conflict with my mod.

I don't have Spad.Next or the hardware CDU, first I heard of it was in the [video](https://www.youtube.com/watch?v=_ZT5rXMJ4Us), but I can take some guesses as to how it's working.

Have you tried running the MCDU SERVER from this package, using your browser instead of Spad.Next and the hardware?    That could help narrow down where the problem is.

**Comment by dementedmonkey** [comment]
Have you made any progress troubleshooting this, or should I close the ticket?

**Comment by dementedmonkey** [comment]
Closing as stale issue.
