### ISSUE TITLE
Websocket management issues?

### ISSUE THREAD

**Issue by BigCow74** [dementedmonkey/cj4-mcdu#13]
Apologies for opening an issue for something I'm not sure is an issue, but I did not know how else to ask this question or contact you.

Do you know if this CJ4 implementation suffers from the performance degradation bug that FBW recently fixed?  Link below.

https://github.com/flybywiresim/a32nx/pull/6947

**Comment by dementedmonkey** [comment]
This will only be an issue if you install this mod and fly the CJ4 without running the websocket server.   

It's probably a bigger issue for the A320 since it's a part of the base mod and you might not be using the external MCDU, where this mod is specifically for the external MCDU, you wouldn't install it if you weren't going to use it.

I see what FBW is doing, I'll see if I can put a similar feature on the Sim setup screen in the CJ4.

**Comment by BigCow74** [comment]
Thanks.  Yes, my question was for the situation where I have your CJ4 mod in my community folder, but decide to not launch the corresponding server app.  Also, CJ4 flights are typically shorter so less likely to arise I suppose.

Thanks for the mod, it's very useful in the CJ4.

**Comment by dementedmonkey** [comment]
It looks like the underlying issue will be fixed by MSFT:

https://forums.flightsimulator.com/t/sim-update-10-beta-release-notes-1-27-9-0/528823

> Fixed a bug where Javascript WebSockets were not closed and released properly when connection failed

**Comment by frankracis-work** [comment]
SU10 is released, and this issue has been fixed

https://forums.flightsimulator.com/t/release-release-notes-1-27-21-0-sim-update-10/543606

Since it's no longer an issue in the sim, I'm going to close the ticket.

**Comment by dementedmonkey** [comment]
SU10 is released, and the issue shows as fixed

https://forums.flightsimulator.com/t/release-release-notes-1-27-21-0-sim-update-10/543606

Since there's no longer a need to work around their bug, I will close this ticket.
