### ISSUE TITLE
Dev dependencies are missing from package.json

### ISSUE THREAD

**Issue by neilenns** [dementedmonkey/cj4-mcdu#33]
The following dev dependencies should be added to package.json:

* @babel/core
* rollup
* postcss

```
npm install --save-dev @babel/core rollup postcss
```

These missing dev dependencies cause build failures in a clean ci/cd environment (not that I'm foreshadowing again...)

**Comment by dementedmonkey** [comment]
What npm version are you using?   Did you get a newer version when you switched to Node 16?

No errors on Node 7.x (Windows) or Node 8.x (Linux).

On my linux machine, the only global packages I have are npm@8.19.1 and corepack@0.12.1.   `npm install` works fine, and if I save the `package-lock.json` and clean the directory, `npm ci` works too.

It looks like these things are getting pulled in as peerDependencies, which have issues in node versions 3 through 6, but are fixed in 7+.

**Comment by neilenns** [comment]
Just gave this a go on my laptop with npm version 9.2.0 and those three packages not included in package.json and it worked. Also gave it a go in ci/cd with node 16.x and it also worked.
